routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DeductionController;
use App\Http\Controllers\RecordController;
use App\Http\Controllers\UserController;
use App\Http\Livewire\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

Route::middleware(['auth:sanctum', 'verified'])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    // Route::get('/users', 'App\Http\Livewire\User\Index@render');

    Route::resources([
        'deductions' => DeductionController::class,
        'records'    => RecordController::class,
        'users'    => UserController::class,
    ]);
});

// Route::resources([
//     'deductions' => DeductionController::class,
//     'records'    => RecordController::class,
// ]);

app/Models/DeductionType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DeductionType extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'description',
        'deduction_category_id',
        'token',
    ];
}

app/Http/Controllers/DeductionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\DeductionType;
use App\Models\DeductionCategory;
use Illuminate\Support\Facades\Redirect;

class DeductionController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $deductions = DeductionType::get();
        $deduction_category_id = "";
        if ($request->deduction_category_id) 
        {
            $deduction_category_id = $request->deduction_category_id;
            $deductions = DeductionType::where('deduction_category_id', $deduction_category_id)->get();
        }
        return view('livewire.deduction.index', [
            'deductions' => $deductions,
            'deduction_categories' => DeductionCategory::get(),
            'deduction_category_id' => $deduction_category_id,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('livewire.deduction.add', ['deduction_categories' => DeductionCategory::get(),]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'description' => 'required',
        ]);

        DeductionType::create($request->all());
    
        return Redirect::route('deductions.index')
        ->with('success','Deduction added succesfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('livewire.deduction.edit', [
            'deduction' => DeductionType::where('id', $id)->first(),
            'deduction_categories' => DeductionCategory::get(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'description' => 'required',
        ]);

        DeductionType::where('id', $id)->update(['description' => $request->description, 'deduction_category_id' => $request->deduction_category_id]);
    
        return Redirect::route('deductions.index')
        ->with('success','Deduction updated succesfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DeductionType::where(['id' => $id])->delete();
        return Redirect::route('deductions.index')
        ->with('delete','Deduction was successfully deleted');
    }
}

app/Http/Livewire/Deduction/Add.php
<?php

namespace App\Http\Livewire\Deduction;

use Livewire\Component;

class Add extends Component
{
    public function render()
    {
        return view('livewire.deduction.add');
    }
}

app/Http/Livewire/Deduction/Edit.php
<?php

namespace App\Http\Livewire\Deduction;

use Livewire\Component;

class Edit extends Component
{
    public function render()
    {
        return view('livewire.deduction.edit');
    }
}

app/Http/Livewire/Deduction/Index.php
<?php

namespace App\Http\Livewire\Deduction;

use Livewire\Component;

class Index extends Component
{
    public function render()
    {
        return view('livewire.deduction.index');
    }
}

app/Http/Livewire/Payslip/Admin.php
<?php

namespace App\Http\Livewire\Payslip;

use Livewire\Component;
use App\Models\DeductionType;
use App\Models\User;
use App\Models\DeductionCategory;

class Admin extends Component
{
    public function render()
    {
        return view('livewire.payslip.admin', [
            'users'                => User::get(),
            'deduction_categories' => DeductionCategory::get(),
        ]);
    }
}

app/Http/Livewire/Payslip/Employee.php
<?php

namespace App\Http\Livewire\Payslip;

use Livewire\Component;
use App\Models\Record;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class Employee extends Component
{
    public function render(Request $request)
    {
        $where_date = $request->date_used ? date('Y-m-t', strtotime($request->date_used)) : date('Y-m-t', strtotime('today'));
        return view('livewire.payslip.employee',[
            'record' => Record::where('user_id', Auth::user()->id)->where('date_used', $where_date)->first(),
            'date_used' => $request->date_used ? date('Y-m', strtotime($request->date_used)) : date('Y-m', strtotime('today')),
            ]);
    }
}

app/Http/Livewire/Record/Add.php
<?php

namespace App\Http\Livewire\Record;

use Livewire\Component;

class Add extends Component
{
    public function render()
    {
        return view('livewire.record.add');
    }
}

app/Http/Livewire/Record/Edit.php
<?php

namespace App\Http\Livewire\Record;

use Livewire\Component;

class Edit extends Component
{
    public function render()
    {
        return view('livewire.record.edit');
    }
}

app/Http/Livewire/Record/Index.php
<?php

namespace App\Http\Livewire\Record;

use Livewire\Component;

class Index extends Component
{
    public function render()
    {
        return view('livewire.record.index');
    }
}

app/Http/Livewire/Record/Show.php
<?php

namespace App\Http\Livewire\Record;

use Livewire\Component;

class Show extends Component
{
    public function render()
    {
        return view('livewire.record.show');
    }
}

app/Http/Livewire/User/Index.php
<?php

namespace App\Http\Livewire\User;

use Livewire\Component;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

class Index extends Component
{
    public function render()
    {
        return view('livewire.user.index', ['users' => User::where('user_type', '>', '1')->get()]);
    }

    public function resetPassword($id)
    {
        dd('test');
        User::where('id', $id)->update(['password' => Hash::make('1234567890')]);
        $this->dispatchBrowserEvent('password-reset');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/livewire/deduction/add.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Deductions') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="grid grid-cols-1 md:grid-cols-2 grid-rows-2 md:grid-rows-2">
                <form method="POST" action="{{ route('deductions.store') }}">
                    @csrf
                    <div class="">
                        <label for="description">Deduction Description</label>
                    </div>
                    <div class="mt-5">
                        <input type="text" name="description" id="description" class="rounded h-1/6">
                    </div>
                    <div class="mt-5">
                        <label for="deduction_category_id">Deduction Category</label>
                    </div>
                    <div class="mt-5">
                        <select name="deduction_category_id" id="deduction_category_id">
                            @foreach($deduction_categories as $deduction_category)
                            <option value="{{ $deduction_category->id }}">{{ $deduction_category->description }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div>
                        <button type="submit" class="bg-blue-500 text-white py-2 px-4 hover:bg-blue-700 rounded-lg mt-5">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/livewire/deduction/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Deductions') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="grid grid-cols-1 md:grid-cols-2 grid-rows-2 md:grid-rows-2">
                <form method="POST" action="{{ route('deductions.update', $deduction->id) }}">
                    @csrf
                    @method('PATCH')
                    <div class="">
                        <label for="description">Deduction Description</label>
                    </div>
                    <div class="mt-5">
                        <input type="text" name="description" id="description" class="rounded h-1/6" value="{{ $deduction->description }}">
                    </div>
                    <div class="mt-5">
                        <label for="deduction_category_id">Deduction Category</label>
                    </div>
                    <div class="mt-5">
                        <select name="deduction_category_id" id="deduction_category_id">
                            @foreach($deduction_categories as $deduction_category)
                                @if ($deduction_category->id == $deduction->deduction_category_id)
                                <option value="{{ $deduction_category->id }}" selected>{{ $deduction_category->description }}</option>
                                @else
                                <option value="{{ $deduction_category->id }}">{{ $deduction_category->description }}</option>
                                @endif
                            @endforeach
                        </select>
                    </div>
                    <div>
                        <button type="submit" class="bg-blue-500 text-white py-2 px-4 hover:bg-blue-700 rounded-lg mt-5">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/livewire/deduction/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Deductions') }}
        </h2>
    </x-slot>
    @if(Session::has('success'))
    <div class="max-w-sm mx-auto sm:px-6 lg:px-8 bg-green-200 mt-2 rounded-lg" role="alert">
        <div class="p-4 text-center text-green-600">
            {{ Session::get('success') }}
        </div>
    </div>
    @endif
    @if(Session::has('delete'))
    <div class="max-w-sm mx-auto sm:px-6 lg:px-8 bg-red-200 mt-2 rounded-lg" role="alert">
        <div class="p-4 text-center text-red-600">
            {{ Session::get('delete') }}
        </div>
    </div>
    @endif
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="mx-auto">
                <a href="{{ route('deductions.create') }}"><button class="bg-blue-500 text-white py-2 px-4 hover:bg-blue-700 rounded-lg">Add</button></a>
                <form method="GET" action="">
                    <div class="text-left">
                        <select name="deduction_category_id" id="deduction_category_id">
                            <option value="">Select Category</option>
                            @foreach($deduction_categories as $deduction_category)
                                @if ($deduction_category->id == $deduction_category_id)
                                <option value="{{ $deduction_category->id }}" selected>{{ $deduction_category->description }}</option>
                                @else
                                <option value="{{ $deduction_category->id }}">{{ $deduction_category->description }}</option>
                                @endif
                            @endforeach
                        </select>
                        <button type="submit" class="bg-blue-500 text-white py-1 px-2 hover:bg-blue-700 rounded-lg mt-5">Search</button>
                    </div>
                </form>
            </div>
            <div class="bg-white overflow-hidden sm:rounded-lg mx-auto w-full">
                <table class="table-fixed border border-black border-collapse mt-5 w-full text-center">
                    <thead>
                        <th class="border border-black w-1/12">ID</th>
                        <th class="border border-black w-2/4">Description</th>
                        <th class="border border-black w-2/4">Category</th>
                        <th class="border border-black w-2/4" colspan="2">Action</th>
                    </thead>
                    <tbody>
                        @foreach($deductions as $deduction)
                        <tr>
                            <td class="border border-black">{{ $deduction->id }}</td>
                            <td class="border border-black">{{ $deduction->description }}</td>
                            <td class="border border-black">{{ $deduction_categories[$deduction->deduction_category_id-1]->description }}</td>
                            <td class="border-b border-black p-2">
                                <a href="{{ route('deductions.edit', $deduction->id) }}"><button class="bg-yellow-500 text-white py-2 px-4 hover:bg-yellow-700 rounded-lg">Edit</button></a>
                            </td>
                            <td class="border-b border-black p-2">
                                <form action="{{ route('deductions.destroy', $deduction->id) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button class="bg-red-500 text-white py-2 px-4 hover:bg-red-700 rounded-lg" type="submit">Delete</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</x-app-layout>